name: "publish temporary npm"

on: 
  push:
    branches:
              main
jobs: 
  release:         
        runs-on: ubuntu-latest  
        permissions:
          packages: write
          contents: read       
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: node
              uses: actions/setup-node@v2
              with:
                  node-version: '14.x'
                  registry-url: 'https://registry.npmjs.org'                 
            - run:  | 
                npm install              
                tsc -p tsconfig.json
                tsc -p tsconfig-cjs.json  
            - run:          
                npm publish --access=public                       
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}            